on:
  push: null
env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  VULKAN_SDK_VERSION: 1.3.268
  WARP_VERSION: 1.0.8
  DXC_RELEASE: v1.7.2308
  DXC_FILENAME: dxc_2023_08_14.zip
  MESA_VERSION: 23.3.1
  CI_BINARY_BUILD: build18
  NIGHTLY_VERSION: nightly-2025-03-06
name: CI
jobs:
  test-with-gpu:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows x86_64
          os: windows-2022
        - name: Mac aarch64
          os: macos-14
        - name: Linux x86_64
          os: ubuntu-22.04
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: $NIGHTLY_VERSION
        components: llvm-tools-preview
    - name: Install cargo-nextest and cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest,cargo-llvm-cov
    - name: caching
      uses: Swatinem/rust-cache@v2
      with:
        key: test-${{ matrix.os }}-ci-test
        workspaces: '. -> target

          xtask -> xtask/target

          '
    - name: (windows) install dxc
      if: matrix.os == 'windows-2022'
      shell: bash
      run: 'set -e


        curl.exe -L --retry 5 https://github.com/microsoft/DirectXShaderCompiler/releases/download/$DXC_RELEASE/$DXC_FILENAME
        -o dxc.zip

        7z.exe e dxc.zip -odxc bin/x64/{dxc.exe,dxcompiler.dll,dxil.dll}


        # We need to use cygpath to convert PWD to a windows path as we''re using bash.

        cygpath --windows "$PWD/dxc" >> "$GITHUB_PATH"

        '
    - name: (windows) install warp
      if: matrix.os == 'windows-2022'
      shell: bash
      run: 'set -e


        # Make sure dxc is in path.

        dxc --version


        curl.exe -L --retry 5 https://www.nuget.org/api/v2/package/Microsoft.Direct3D.WARP/$WARP_VERSION
        -o warp.zip

        7z.exe e warp.zip -owarp build/native/amd64/d3d10warp.dll


        mkdir -p target/llvm-cov-target/debug/deps


        cp -v warp/d3d10warp.dll target/llvm-cov-target/debug/

        cp -v warp/d3d10warp.dll target/llvm-cov-target/debug/deps

        '
    - name: (windows) install mesa
      if: matrix.os == 'windows-2022'
      shell: bash
      run: 'set -e


        curl.exe -L --retry 5 https://github.com/pal1000/mesa-dist-win/releases/download/$MESA_VERSION/mesa3d-$MESA_VERSION-release-msvc.7z
        -o mesa.7z

        7z.exe e mesa.7z -omesa x64/{opengl32.dll,libgallium_wgl.dll,libglapi.dll,vulkan_lvp.dll,lvp_icd.x86_64.json}


        cp -v mesa/* target/llvm-cov-target/debug/

        cp -v mesa/* target/llvm-cov-target/debug/deps


        # We need to use cygpath to convert PWD to a windows path as we''re using bash.

        echo "VK_DRIVER_FILES=`cygpath --windows $PWD/mesa/lvp_icd.x86_64.json`" >> "$GITHUB_ENV"

        echo "GALLIUM_DRIVER=llvmpipe" >> "$GITHUB_ENV"

        '
    - name: (linux) install vulkan sdk
      if: matrix.os == 'ubuntu-22.04'
      shell: bash
      run: 'set -e


        sudo apt-get update -y -qq


        # vulkan sdk

        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -

        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-$VULKAN_SDK_VERSION-jammy.list https://packages.lunarg.com/vulkan/$VULKAN_SDK_VERSION/lunarg-vulkan-$VULKAN_SDK_VERSION-jammy.list


        sudo apt-get update

        sudo apt install -y vulkan-sdk

        '
    - name: (linux) install mesa
      if: matrix.os == 'ubuntu-22.04'
      shell: bash
      run: "set -e\n\ncurl -L --retry 5 https://github.com/gfx-rs/ci-build/releases/download/$CI_BINARY_BUILD/mesa-$MESA_VERSION-linux-x86_64.tar.xz\
        \ -o mesa.tar.xz\nmkdir mesa\ntar xpf mesa.tar.xz -C mesa\n\n# The ICD provided by the mesa build\
        \ is hardcoded to the build environment.\n#\n# We write out our own ICD file to point to the mesa\
        \ vulkan\ncat <<- EOF > icd.json\n{\n  \"ICD\": {\n      \"api_version\": \"1.1.255\",\n     \
        \ \"library_path\": \"$PWD/mesa/lib/x86_64-linux-gnu/libvulkan_lvp.so\"\n  },\n  \"file_format_version\"\
        : \"1.0.0\"\n}\nEOF\n\necho \"VK_DRIVER_FILES=$PWD/icd.json\" >> \"$GITHUB_ENV\"\necho \"LD_LIBRARY_PATH=$PWD/mesa/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH\"\
        \ >> \"$GITHUB_ENV\"\necho \"LIBGL_DRIVERS_PATH=$PWD/mesa/lib/x86_64-linux-gnu/dri\" >> \"$GITHUB_ENV\"\
        \n"
    - name: disable debug
      shell: bash
      run: 'mkdir -p .cargo

        echo """

        [profile.dev]

        debug = 1" >> .cargo/config.toml

        '
    - name: run tests
      shell: bash
      run: 'set -e

        cargo llvm-cov --workspace --lcov --output-path lcov.info --all-features --doctests

        '
    - name: generate coverage report
      id: coverage
      shell: bash
      continue-on-error: true
      run: 'set -e


        cargo llvm-cov report --lcov --output-path lcov.info

        '
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-cases-${{ matrix.os }}
        path: ./test_cases
    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v3
      if: steps.coverage.outcome == 'success'
      with:
        files: lcov.info
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'B-pr-num' }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: $NIGHTLY_VERSION
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - name: format style check
      run: cargo fmt --all -- --check
    - name: cargo clippy check
      run: cargo clippy --all-targets --all-features -- -D warnings
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - run: cargo check
      id: _bre_lint
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: build ribir
      run: cargo build
    - name: compile doc examples
      run: "{\n  echo ./README.md\n  find \"./docs\" -name \"*.md\"\n} |  xargs -I {} rustdoc --test {}\
        \ -L target/debug/deps/  --edition 2018 --extern ribir=target/debug/libribir.rlib\n"
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
    - name: compile to wasm
      run: cargo build --workspace --target wasm32-unknown-unknown --exclude ribir_dev_helper
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
    - name: Run wasm test of core
      run: wasm-pack test --headless --chrome ./core
      if: '!cancelled() && steps._bre_lint.conclusion == ''success'''
